export const weekDays = [
  "Samedi",
  "Dimanche",
  "Lundi",
  "Mardi",
  "Mercredi",
  "Jeudi",
  "Vendredi"
] as const;

export const algeriaWilayas = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Bejaia",
  "Biskra",
  "Bechar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tebessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Setif",
  "Saida",
  "Skikda",
  "Sidi Bel Abbes",
  "Annaba",
  "Guelma",
  "Constantine",
  "Medea",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arreridj",
  "Boumerdes",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Ain Defla",
  "Naama",
  "Ain Temouchent",
  "Ghardaia",
  "Relizane",
  "Timimoun",
  "Bordj Badji Mokhtar",
  "Ouled Djellal",
  "Beni Abbes",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "El M'Ghair",
  "El Meniaa"
] as const;

export const communesByWilaya: Record<string, string[]> = {
  Alger: ["Alger Centre", "Bab El Oued", "Bir Mourad Rais", "Bouzareah", "Cheraga", "Dar El Beida", "Draria", "El Biar", "Hussein Dey", "Kouba"],
  Oran: ["Oran", "Bir El Djir", "Es Senia", "Arzew", "Ain El Turk", "Mers El Kebir", "Gdyel", "Bethioua"],
  Constantine: ["Constantine", "El Khroub", "Hamma Bouziane", "Ain Smara", "Didouche Mourad", "Zighoud Youcef"],
  Annaba: ["Annaba", "El Bouni", "Seraidi", "Berrahal", "El Hadjar"],
  Blida: ["Blida", "Boufarik", "Bouinan", "Mouzaia", "Beni Mered", "Ouled Yaich"],
  Bejaia: ["Bejaia", "Akbou", "Amizour", "Kherrata", "Seddouk", "Tichy"],
  Setif: ["Setif", "El Eulma", "Ain Oulmene", "Bougaa", "Salah Bey"],
  Batna: ["Batna", "Barika", "Ain Touta", "Merouana", "Arris"],
  Tlemcen: ["Tlemcen", "Maghnia", "Remchi", "Ghazaouet", "Nedroma"],
  "Tizi Ouzou": ["Tizi Ouzou", "Draa Ben Khedda", "Azazga", "Ain El Hammam", "Tigzirt"],
  Boumerdes: ["Boumerdes", "Dellys", "Boudouaou", "Thenia", "Khemis El Khechna"],
  Tipaza: ["Tipaza", "Kolea", "Cherchell", "Hadjout", "Fouka"],
  Skikda: ["Skikda", "Azzaba", "Collo", "El Harrouch", "Tamalous"],
  Mostaganem: ["Mostaganem", "Ain Tedeles", "Sidi Ali", "Mazagran", "Kheir Eddine"],
  Medea: ["Medea", "Berrouaghia", "Ksar El Boukhari", "Ain Boucif", "Tablat"],
  Chlef: ["Chlef", "Tenes", "Oued Fodda", "Boukadir", "Abou El Hassan"]
};

export const doctorAvatarIcons = [
  { value: "stethoscope", label: "Stethoscope" },
  { value: "cross", label: "Croix medicale" },
  { value: "heart", label: "Coeur" },
  { value: "pill", label: "Comprime" }
] as const;
